### ISSUE TITLE
Erro exercício 01 - encodding 

### ISSUE THREAD

**Issue by Ladeia** [quatroka/mentoria-practice#1]
File "run.py", line 6
SyntaxError: Non-ASCII character '\xc3' in file run.py on line 6, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by quatroka** [comment]
Tentativa de resolução em: a09b88538b15a94262cdc080f032e202a9a1ef79

**Comment by Ladeia** [comment]
Muito bem!
