### ISSUE TITLE
Erro exercício 2 - entrada inválida

### ISSUE THREAD

**Issue by Ladeia** [quatroka/mentoria-practice#2]
mentoria-practice/psets/pset2$ python run.py 
===============
Move to Foward: F
Rotate to Left: L
Rotate to Right: R
===============
Insert the sequence of moves: 
F
Traceback (most recent call last):
  File "run.py", line 12, in <module>
    ROBOT.read_and_execute_movement(input())
  File "<string>", line 1, in <module>
NameError: name 'F' is not defined

**Comment by quatroka** [comment]
Tentativa de resolução em: a09b88538b15a94262cdc080f032e202a9a1ef79

**Comment by Ladeia** [comment]
Acredito que esse link é do outro exercício, não?

**Comment by Ladeia** [comment]
Acredito que esse link é do outro exercício, não?

**Comment by quatroka** [comment]
Acho que somente o correção de enconding resolve o problema.

**Comment by Ladeia** [comment]
Funcionou bem, parabéns!
